name: My Custom Workflow

on:
  push:
    branches:
      - master  # O la rama que prefieras

jobs:
  build:
    runs-on: self-hosted  # Aquí se asigna el trabajo al agente autoalojado

    steps:
      - name: Run custom build
        run: echo "Running my custom build script!"
